name: Build & Package (install + artifact)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "Runner: $RUNNER_OS"
          node --version || true
          npm --version || true
          echo "---- package.json (top) ----"
          if [ -f package.json ]; then jq 'del(.dependencies, .devDependencies) | .scripts' package.json || cat package.json | head -n 50 ; else echo "no package.json"; fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (ci)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Determine & run build command (tries common options)
        id: buildstep
        run: |
          BUILD_CMD="$(node -e \"const fs=require('fs'); try{const p=require('./package.json'); if(p.scripts && p.scripts.build){console.log('npm run build');} else { const deps = Object.assign({}, p.dependencies||{}, p.devDependencies||{}); if(deps.vite){console.log('npm run build || npx vite build')} else if(deps['react-scripts']){console.log('npm run build')} else if(deps.next){console.log('npm run build')} else if(deps.gatsby){console.log('npm run build')} else if(deps.parcel){console.log('npx parcel build')} else {console.log('')} }}catch(e){console.log('')}\")"
          echo "Selected build command: [$BUILD_CMD]"
          echo "cmd=$BUILD_CMD" >> $GITHUB_OUTPUT
          if [ -n "$BUILD_CMD" ]; then
            bash -lc "$BUILD_CMD" || echo "Build command failed (nonfatal)";
          else
            echo "No build command detected, skipping build step."
          fi

      - name: List top-level files and find build outputs (debug)
        run: |
          echo "---- ls -la (root) ----"
          ls -la
          echo "---- find common build dirs ----"
          find . -maxdepth 3 -type d \( -name dist -o -name build -o -name out -o -name public -o -name '.next' -o -name '.output' \) -print || true
          echo "---- sizes of candidate dirs ----"
          for d in dist build out public .next .output; do if [ -d "$d" ]; then echo ">>> $d"; du -sh "$d" || true; fi; done

      - name: Collect build artifact paths
        id: collect
        run: |
          ARTPATHS=""
          for d in dist build out public .next .output; do
            if [ -d "$d" ] && [ "$(ls -A $d 2>/dev/null)" ]; then
              ARTPATHS="$ARTPATHS $d"
            fi
          done
          if [ -f index.html ] && [ -z "$ARTPATHS" ]; then
            ARTPATHS="$ARTPATHS index.html"
          fi
          # Trim leading space
          ARTPATHS="$(echo $ARTPATHS | sed -e 's/^ //')"
          echo "paths=$ARTPATHS" >> $GITHUB_OUTPUT
          echo "Found artifact paths: [$ARTPATHS]"
      
      - name: Upload build output (if any)
        if: ${{ steps.collect.outputs.paths != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ steps.collect.outputs.paths }}

      - name: Create node_modules.zip fallback (if no build output)
        if: ${{ steps.collect.outputs.paths == '' }}
        run: |
          echo "No build output found; creating node_modules.zip as fallback (may be large)."
          rm -f node_modules.zip
          if [ -d node_modules ]; then
            zip -r node_modules.zip node_modules || true
            ls -lh node_modules.zip || true
          else
            echo "No node_modules present."
          fi

      - name: Upload node_modules zip (fallback)
        if: ${{ steps.collect.outputs.paths == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: node_modules-zip
          path: node_modules.zip

      - name: Create debug files (package.json + filelist)
        run: |
          ls -la > filelist.txt
          if [ -f package.json ]; then
            echo "---- package.json ----" > packagejson.txt
            cat package.json >> packagejson.txt
          else
            echo "no package.json" > packagejson.txt
          fi

      - name: Upload debug files (package.json + filelist)
        uses: actions/upload-artifact@v4
        with:
          name: debug-info
          path: |
            filelist.txt
            packagejson.txt

